C_SOURCES = mypuck_supervisor.c randommove.c analysebehavior.c protocol.c
CFLAGS    = -W -O3
#CFLAGS    = -W -g -pg -O3
#LIBRARIES = -gdb -pg

include $(WEBOTS_HOME)/projects/default/controllers/Makefile.include
